os:
- linux

language: php

php:
- '7.0'

before_script:
  - composer self-update
  - composer install --no-interaction
  # Install dependencies
  - bash ci/docker_install.sh > /dev/null

test:app:
  script:
  - echo "hello world!"